#!/bin/sh
### BEGIN INIT INFO
# Provides:          swupdater
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: swupdater
# Description:       IOT swupdater
### END INIT INFO
# ------------------------------------------------------------------
# Author:    nlv10677
# Copyright: NXP B.V. 2014. All rights reserved
# ------------------------------------------------------------------

START=99

PROG=iot_su.sh

do_start () {
	echo Starting /usr/bin/$PROG
	if [ -z `pidof $PROG` ]; then
		/usr/bin/$PROG > /dev/null &
	fi
}

do_stop () {
	echo Will not stop $PROG, must do by hand
}
#-$1既是外部传参的值，如：运行该脚本的时候：./test.sh apple
#- 满足条件后需要使用双分号跳出结构 ;;
#-* 表示以上都不匹配时执行
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  *)
	echo "Usage: $PROG [start|stop]" >&2
	exit 3
	;;
esac
