# ------------------------------------------------------------------
# Build all IoT test software
# ------------------------------------------------------------------
# Author:    nlv10677
# Copyright: NXP B.V. 2014. All rights reserved
# ------------------------------------------------------------------

all:
	cd OutTesting;  make
	cd JoinTest;    make
	cd ControlTest; make
	cd PlugTest;    make
	cd GwTest;      make
	cd Se;          make
	cd LogTail;     make

build:
	cd OutTesting;  make build
	cd JoinTest;    make build
	cd ControlTest; make build
	cd PlugTest;    make build
	cd GwTest;      make build
	cd Se;          make build
	cd LogTail;     make build

clean:
	cd OutTesting;  make clean
	cd JoinTest;    make clean
	cd ControlTest; make clean
	cd PlugTest;    make clean
	cd GwTest;      make clean
	cd Se;          make clean
	cd LogTail;     make clean

